### ISSUE TITLE
Lab 01 will not open

### ISSUE THREAD

**Issue by jamiepalka** [Sta199-S18/community#10]
Hi! I did about half of the lab instructions yesterday, and I came back to finish today, but my lab will not open.  I get to the project page of RStudio with no problems, but when I click on lab 01, it says "Please wait" continuously (about an hour now). I've tried multiple different wifi's and browsers.  Is there anything I can do to combat this? Thank you!  @mine-cetinkaya-rundel @WalkerHarrison @peterbhase

**Comment by mine-cetinkaya-rundel** [comment]
Taking a look right now

**Comment by mine-cetinkaya-rundel** [comment]
While I try to diagnose the technical issue, could you let me know if you had pushed all of your changes to github already? @jamiepalka

**Comment by jamiepalka** [comment]
@mine-cetinkaya-rundel Yes! I Have pushed all changes.

**Comment by jamiepalka** [comment]
@mine-cetinkaya-rundel Thank you!

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka Ok if your project still isn't opening up, here is my suggestion:

- Go to your GitHub repository for this lab: You should be able to find it at https://github.com/Sta199-S18
- Grab its URL the same way you have done before
- Create a new project on RStudio Cloud. All of your changes will come back, including your git history, because you've already pushed them all. This is one perk of using version control.

Let me know if you run into any further issues!

**Comment by jamiepalka** [comment]
@mine-cetinkaya-rundel That worked! Thank you! Will I need to go back through the lab and redo some parts, like linking it to my git account and importing packages?

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka Yes, I'm afraid you will. You might as well do it preemptively, but say you forgot:

- it would tell you some package not found when you tried to knit the document -- and hence you'd know you need to re-install it
- it would tell you git isn't configured when you tried to commit -- and hence you'd know you need to configure it

But it's always nerve-wrecking to see errors so preemptively doing it makes sense.

You could delete your old project in RStudio Cloud that is not working, but you don't have to. We will be doing the grading based on what's on GitHub so it doesn't matter if there is a semi-completed project on Cloud (you just might want to if you'd like your account to be well organized).

**Comment by jamiepalka** [comment]
@mine-cetinkaya-rundel Ok! Will I have to do these things each time, or do I just have to redo them because I created a new copy of the project?

**Comment by mine-cetinkaya-rundel** [comment]
You need to do them for each project. But this usually means for each assignment. (I am however working with the RStudio Cloud designers to eliminate this need, but for now, yes.)

**Comment by jamiepalka** [comment]
@mine-cetinkaya-rundel Thank you so much for all of your help!

**Comment by mine-cetinkaya-rundel** [comment]
@jamiepalka you're welcome, sorry about the technical troubles!
